Replace . typo with - in paths-from-file example
newren/git-filter-repo pull request #239
Opened 2021-04-17 05:50 UTC by Codym48

The "Filtering based on many paths" section includes this code snippet,
```
# An example that is like --path-regex:
regex:^.*/.*/[0-9]{4}-[0-9]{2}-[0-9]{2}.txt$
```
and this  text, 

> files whose name was of the form YYYY.MM-DD.txt at least two subdirectories deep

Update the text to YYYY-MM-DD.txt to match the regex in the code snippet.

2021-06-05 18:45 UTC, newren commented
Sweet, thanks for catching this!

Could you add your Signed-off-by to the commit message, and use a real email address for recording the commit?

Also, if you could prepend the first line of the commit message with `git-filter-repo.txt: `, that'd be great, but I'd be happy to fix that up for you if you can add the Signed-off-by and fix the email address.

2021-06-05 19:20 UTC, newren requested changes
Marking as needing changes for the Signed-off-by and email addresses.

2021-06-08 05:56 UTC, Codym48 commented
Today I learned about the Signed-off-by trailer (https://git.kernel.org/pub/scm/git/git.git/tree/Documentation/SubmittingPatches#n305) and the SCO lawsuits that preceded it (https://stackoverflow.com/a/1962112/2597078) and read the rest of the contribution guidelines and tried to do some line wrapping in the process.

Thanks for your patience

2021-06-08 06:38 UTC, newren approved these changes

2021-06-08 06:38 UTC, merged

2021-06-08 06:38 UTC, newren commented
Thanks for the contribution!