Allow callback body to be loaded from a file
newren/git-filter-repo pull request #246
Opened 2021-04-27 12:44 UTC by bulldy80

For anything more complicated than a few lines, it's easier to write the
callback body in a file and let filter-repo load the file as a string.

2021-06-05 23:29 UTC, newren requested changes
Sorry for taking a while to get back to you.

I was going to say that you can already have callbacks in other files by just having other files import git_filter_repo.py; contrib/filter-repo-demos/barebones-example and the other examples in that directory show how to do it.  But this was so cleanly done that it just seems like a net win.  Well done.

I do need one thing, though; can you amend the commit to add your Signed-off-by as per https://git.kernel.org/pub/scm/git/git.git/tree/Documentation/SubmittingPatches#n305?  If you can do that, I'll be happy to merge the change.

2021-06-06 10:25 UTC, bulldy80 commented
> Sorry for taking a while to get back to you.
> 
> I was going to say that you can already have callbacks in other files by just having other files import git_filter_repo.py; contrib/filter-repo-demos/barebones-example and the other examples in that directory show how to do it. But this was so cleanly done that it just seems like a net win. Well done.

Thanks!


> I do need one thing, though; can you amend the commit to add your Signed-off-by as per https://git.kernel.org/pub/scm/git/git.git/tree/Documentation/SubmittingPatches#n305? If you can do that, I'll be happy to merge the change.

Done, thanks again!

2021-06-07 15:28 UTC, newren approved these changes

2021-06-07 15:38 UTC, newren commented
I tweaked the commit to include a testcase so we kept git-filter-repo at 100% line coverage, and merged the result manually. 
 You can see the modified commit at 5256c99e496b (Allow callback body to be loaded from a file, 2021-04-27).

Thanks for the contribution!

2021-06-07 15:38 UTC, closed without merging