Update mandb after installing the man page
newren/git-filter-repo pull request #299
Opened 2021-10-29 19:24 UTC by erickeller

when installing manually the manpage, one shall also update the mandb

2021-11-09 06:50 UTC, newren requested changes
Hi, thanks for the suggestion!  Could you add a Signed-off-by trailer to your commit message so I can include it?  While at it, could you change the second sentence/paragraph of the commit message to fix up the grammar a bit; perhaps:

"When manually installing the manpage, also update the mandb."

If you can do so, I'll be happy to include the change.

2021-12-01 20:15 UTC, erickeller commented
I did also add the trigger of mandb if the command exists in the Makefile

2021-12-01 21:04 UTC, newren approved these changes

2021-12-01 21:04 UTC, merged

2021-12-01 21:04 UTC, newren commented
Thanks!