lint-history: add --refs argument
newren/git-filter-repo pull request #316
Opened 2021-12-30 22:51 UTC by rhaschke

Unfortunately, `lint-history` is missing most standard arguments of `git-filter-repo`. I was particularly missing `--refs` to limit history rewrite to a subset of commits. This simple change here solved that issue for me.
However, probably there is a better way to provide standard arguments in `lint-history` as well. Please feel free to adapt this PR accordingly.

2022-09-24 22:58 UTC, newren requested changes
Hi!

Sorry for the long delay.  :-(

The changes look interesting, just a few minor tidbits:
  * Commit messages need to have your Signed-off-by line on them for me to include the changes
  * Lines of code should be wrapped at 80 characters.
  * You copied the description from git-filter-repo, which mentions "--partial", but "--partial" is not an option to line-history.  You'll need to reword it a bit, perhaps refering to git-filter-repo's manual and options instead.

If you can make those fixes, I'd be happy to merge your changes.

2022-09-25 08:30 UTC, rhaschke commented
* > Commit messages need to have your Signed-off-by line on them for me to include the changes

  Done now. I suggest setting up the [DCO app](https://github.com/apps/dco) to enforce that automatically.
* > Lines of code should be wrapped at 80 characters.

  There are many lines that are way longer :wink: I shortened the text anyway.
<details>
<summary><code>awk '{print length}' git_filter_repo.py | sort -n | uniq -c</code></summary>
<table>
	<thead>
		<tr><th>count</th><th>length</th></tr>
	</thead>
	<tbody>
		<tr><td>10</td><td>81</td></tr>
		<tr><td>8</td><td>83</td></tr>
		<tr><td>2</td><td>84</td></tr>
		<tr><td>3</td><td>85</td></tr>
		<tr><td>2</td><td>87</td></tr>
		<tr><td>1</td><td>88</td></tr>
		<tr><td>1</td><td>89</td></tr>
		<tr><td>2</td><td>90</td></tr>
		<tr><td>1</td><td>92</td></tr>
		<tr><td>1</td><td>94</td></tr>
		<tr><td>1</td><td>97</td></tr>
		<tr><td>1</td><td>100</td></tr>
		<tr><td>2</td><td>101</td></tr>
		<tr><td>1</td><td>110</td></tr>
		<tr><td>1</td><td>115</td></tr>
		<tr><td>1</td><td>124</td></tr>
		<tr><td>1</td><td>127</td></tr>
		<tr><td>1</td><td>134</td></tr>
	</tbody>
</table>
</details>

* > You copied the description from git-filter-repo, which mentions "--partial", but "--partial" is not an option to line-history.  You'll need to reword it a bit, perhaps refering to git-filter-repo's manual and options instead.

  Done. Hope it's better now.

2022-09-25 09:34 UTC, rhaschke commented
Hm. I just noticed that this doesn't work (anymore?). Having `args.refs` defined doesn't call the callback anymore!
Looks like, my approach was too naive.

2022-09-26 16:07 UTC, newren commented
Hi,

Thanks for fixing it up.  Yes, I know I've got some lines more than 80 characters long; it's not a completely rigid rule, but a general aim (see also https://github.com/git/git/blob/4fd6c5e44459e6444c2cd93383660134c95aabd1/Documentation/CodingGuidelines#L199).

Could you squash the 3 patches?  They're all one logical change.  Also, the 3rd patch is missing a Signed-off-by, but that problem becomes obsolete once you squash.  :-)

2022-09-29 13:24 UTC, rhaschke commented
> Could you squash the 3 patches?

Done. You know that you can squash-merge commits directly from github, don't you?

2022-09-29 16:24 UTC, merged

2022-09-29 16:25 UTC, newren commented
> > Could you squash the 3 patches?
> 
> Done. You know that you can squash-merge commits directly from github, don't you?

[Of course I am](https://public-inbox.org/git/CABPp-BEcpasV4vBTm0uxQ4Vzm88MQAX-ArDG4e9QU8tEoNsZWw@mail.gmail.com/).  Bad practice in general (folks should create clean commits), and totally irrelevant here anyway since you were missing your Signed-off-by on the third commit.

Anyway, thanks for cleaning up; I've merged now.