Fix path of git-filter-repo.(1|html)
newren/git-filter-repo pull request #333
Opened 2022-02-03 10:39 UTC by mattiasdrp

Since they are not at the root of the repo but in Documentation/(man1 | html) (the Makefile puts them here and the last releast tarball has them in it too)

2022-09-25 00:38 UTC, newren requested changes
Hi,

Sorry for taking so long to respond.

The changes make sense.  The commit message needs a little work -- lines should be wrapped at 72 characters, and I need a Signed-off-by line and a real email address to include the changes.  Could you update the commit to fix these?

2022-09-25 08:28 UTC, mattiasdrp commented
Hi,
No worries, we all have a lot of things to do :-)
I fixed my commit to include the changes
Thanks for this nice package

2022-09-26 15:56 UTC, newren commented
Hi,

Thanks for understanding, and I'm glad you've enjoyed the package.

Thanks for fixing the wrapping and adding a Signed-off-by.  It appears you've used a username rather than a real name, though.  Is that right?  As per https://github.com/git/git/blob/4fd6c5e44459e6444c2cd93383660134c95aabd1/Documentation/SubmittingPatches#L284-L286, I unfortunately need a real name for signoff.  (And the author and committer should match the Signed-off-by as well.)  Can you fix that?

2022-09-26 16:49 UTC, mattiasdrp commented
I'm not very fond of letting my real name everywhere on the Internet. I don't mind you taking the ownership of this PR and merging it with your name though so ;-)

2022-09-26 17:20 UTC, closed without merging